### ISSUE TITLE
avrdude: stk500_getsync(): not in sync: resp=0x00

### ISSUE THREAD

**Issue by TheBossCookie** [damellis/attiny#28]
what do i do to fix this????

**Comment by herbkanis** [comment]
Some additional things to think about:
Try running the programmer from a different OS. I was using Windows7 64 bit and things worked fine until one day and got sync errors ever since. Drove me nuts for several days until I moved to another computer (hot day and needed the AC on). The XP machine worked fine!! I must have installed something and it mucked up the USB config.
Wasn’t the chip or the code or the circuit… it was Windows 7.
