### ISSUE TITLE
Create a README with git installation instructions (and a link to the HLT tutorial).

### ISSUE THREAD

**Issue by muessigb** [damellis/attiny#92]
It shows attiny in the board menu and that's it.
No further selection.

**Comment by damellis** [comment]
What version of Arduino are you using? How did you install the ATtiny support? Do you see Clock and Processor menus in Tools?

**Comment by Muessigb** [comment]
Given that there is no readme, I have no idea what to do. I initially tried it with Arduino 1.0.5 and now updated to 1.6.7.

**Comment by damellis** [comment]
There's a tutorial here: http://highlowtech.org/?p=1695. You may have better luck using the boards manager to install the ATtiny support. Otherwise, you probably need to move the ATtiny files into an avr sub-folder, so you have something like: ~/Documents/Arduino/hardware/attiny/avr/boards.txt, etc.

**Comment by brunobasto** [comment]
+1 for having a README.MD. Could even be just a copy of what's in http://highlowtech.org/?p=1695

**Comment by damellis** [comment]
Fixed by 78bf576cf5d4159f6957df24564476eb691f8734
